export default {
    "success": true,
    "forms":
    [
        {
            "id": "1",
            "form":
            {   
                "name":"Jazz",
                "img":"../images/jeremy-bishop-cvkFJdc_IpI-unsplash.jpg",
                "courses":
                [
                    {
                        "name":"Gaytri",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Sushi",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Sans",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    }
                ]
            }

        },
        {
            "id": "2",
            "form":
            {   
                "name":"Hip-Hop",
                "img":"https://imgs.search.brave.com/t8SIp47odK-x_q0oE60v9N4AfueDWlO6R9RgzULefNQ/rs:fit:713:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5L/Zmx2TGotaElUR3la/ZUtxblNUS0ZnSGFF/NyZwaWQ9QXBp",
                "courses":
                [
                    {
                        "name":"Course1",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course2",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course3",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    }
                ]
            }
        },
        {
            "id": "3",
            "form":
            {   
                "name":"Shuffle",
                "img":"https://images.unsplash.com/photo-1454486837617-ce8e1ba5ebfe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8ZGFuY2luZ3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
                "courses":
                [
                    {
                        "name":"Course1",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course2",
                        "thumnail":"https://i.ytimg.com/vi/yBZ0Y2t0ceo/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAw8FxCpbgf6bsoJEWKKfBpMra7vA",
                        "course":"https://www.youtube.com/playlist?list=PL0m7UHzPZEA-sSPCcp0EJrryE_HVshXsu"
                    },
                    {
                        "name":"Course3",
                        "thumnail":"https://i.ytimg.com/vi/VJOVDXK7V5E/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBgXAqgk_bIO1JnG-ciDAiRSBtXXQ",
                        "course":"https://www.youtube.com/playlist?list=PLpJRb_Th3m5Qr5qzW6T_ZZ7L06kq17W0E"
                    },
                    {
                        "name":"Course4",
                        "thumnail":"https://i.ytimg.com/vi/VJOVDXK7V5E/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBgXAqgk_bIO1JnG-ciDAiRSBtXXQ",
                        "course":"https://www.youtube.com/playlist?list=PLpJRb_Th3m5Qr5qzW6T_ZZ7L06kq17W0E"
                    },
                    {
                        "name":"Course5",
                        "thumnail":"https://i.ytimg.com/vi/VJOVDXK7V5E/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBgXAqgk_bIO1JnG-ciDAiRSBtXXQ",
                        "course":"https://www.youtube.com/playlist?list=PLpJRb_Th3m5Qr5qzW6T_ZZ7L06kq17W0E"
                    }
                ]
            }
        },
        {
            "id": "4",
            "form":
            {   
                "name":"Popping",
                "img":"https://imgs.search.brave.com/xW_lIWh5HeSWZ31anpA106bCGekOFyxn5xofNbHeCEQ/rs:fit:777:225:1/g:ce/aHR0cHM6Ly90c2U0/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5X/ZFNMWWg2ZlVTMVFU/SjJMUWxBNEt3SGFF/aCZwaWQ9QXBp",
                "courses":
                [
                    {
                        "name":"Course1",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course2",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course3",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    }
                ]
            }
        },
        {
            "id": "5",
            "form":
            {   
                "name":"Salsa",
                "img":"https://imgs.search.brave.com/23ClQKCqDQkyRzGLPqZMZ5XV-AeecOGXXBnOQhWNoic/rs:fit:711:225:1/g:ce/aHR0cHM6Ly90c2U0/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5z/MVpWVzZ3bldUNG94/ZTgwR3hVTXBnSGFF/OCZwaWQ9QXBp",
                "courses":
                [
                    {
                        "name":"Course1",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course2",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course3",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    }
                ]
            }
        },
        {
            "id": "6",
            "form":
            {   
                "name":"Contemporary",
                "img":"https://imgs.search.brave.com/r1io75jg2AX1IvKqAphSkO8GnJE5vdZLLnVpMAcl4mI/rs:fit:713:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5m/Vk9nVmx1aXdNQnhw/WmVzRENtaDRBSGFF/NyZwaWQ9QXBp",
                "courses":
                [
                    {
                        "name":"Course1",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course2",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    },
                    {
                        "name":"Course3",
                        "thumnail":"https://i.ytimg.com/vi/Kt-Tb9gaOB8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC9XWDrmCvXPrzcO7Gs0LunZbZgwQ",
                        "course":"https://www.youtube.com/playlist?list=PLCt36-edE8ZAo2ituccnDskAmDCnvrdt6"
                    }
                ]
            }
        }

    ]
}